### ISSUE TITLE
The FFB Capabilities

### ISSUE THREAD

**Issue by huseyinctlbs** [YukMingLaw/ArduinoJoystickWithFFBLibrary#1]
Hi. You have written the name of this repo as joystick with ffb but i couldnt see any connection between the joystick library and the descriptor. Are you working on it? Im trying to find a easy way to do it too. But i dont know yet.

**Comment by YukMingLaw** [comment]
Hi,I will update this repo later on.The update includes the examples that how to use this library.I have made a force feedback wheel with this library,it works nice.

**Comment by YukMingLaw** [comment]
The example code and the readme have been added.
