### ISSUE TITLE
Multi axis damper, friction and intertia

### ISSUE THREAD

**Issue by pkaser** [YukMingLaw/ArduinoJoystickWithFFBLibrary#4]
Can you elaborate your documentation on how to use friction, damper, spring and intertia in a multi axis environment?

**Comment by YukMingLaw** [comment]
I updated the library.It changed a lot.And now it suit to multi-axis environment finally.
I have tested it and no bugs temporary.

**Comment by pkaser** [comment]
I'm using your updated code. Im asking if you could improve the documentation on how to implement it.

**Comment by pkaser** [comment]
Ok, that latest example code in the read me helped. I was expecting and x and y axis spring, damper, etc settings to be separate properties.
