### ISSUE TITLE
Question regarding Encoder and the driver dll used.

### ISSUE THREAD

**Issue by eglische** [YukMingLaw/ArduinoJoystickWithFFBLibrary#60]
G'day
I apologize if i missed this, but i haven’t found references to what encoder is used in the demos. As we got a 5v and two phases, i assume it’s a rotary encoder (PPR type), is the pulse per revolution not important? My C skills don’t permit me to read the digitalwritefast lib and i suspect the answer to this question is there.

On a additional note, it would be very nice to ask if it’s possible (or because of resolution advisable) to replace the (bulky) PPR type encoder with a hall sensor like a p3022-v1-cw360 because of it’s footprint for that matter.

Second question is the ffb feedback source, will it work with the standard feedback just like a Microsoft Force Feedback stick - i.e. work with the Sidewinder Force Feedback  2 Driver (pid.dll) ?

Thanks for your patience.
Yeti

**Comment by numpad0** [comment]
PPR shouldn't be important, calibration through Win+R -> `joy.cpl` can take care of that as well as range problems.
